In [2]:

import os
import sys
from pyamff.fingerprints.ewald_FPs import Ewald_FPs
import torch

In [ ]:
from ase.io import read, Trajectory, write

center = read('/mnt/d/Alan/PhD/pyamff_training/Ge/pyamff_all_2.extxyz', index='0')
write('../Ge/train0.traj', center)

In [3]:
model_path = '../Ge/pyamff_100.pt'

loaded = torch.load(model_path)
loaded['state_dict']

OrderedDict([('nn_models.Ge.inputLayer.weight',
              tensor([[-0.4979,  0.1831, -1.1852,  0.4070],
                      [-3.8636, -1.2590,  0.4188,  1.0634]], dtype=torch.float64)),
             ('nn_models.Ge.inputLayer.bias',
              tensor([-0.8155, -1.8666], dtype=torch.float64)),
             ('nn_models.Ge.hiddenLayer_1.weight',
              tensor([[ 0.6491, -2.6857],
                      [-2.3191, -3.6749]], dtype=torch.float64)),
             ('nn_models.Ge.hiddenLayer_1.bias',
              tensor([1.9762, 1.7285], dtype=torch.float64)),
             ('nn_models.Ge.outputLayer.weight',
              tensor([[-0.2476, -2.3567],
                      [-0.1735, -0.6242]], dtype=torch.float64)),
             ('nn_models.Ge.outputLayer.bias',
              tensor([ 2.5087, -0.0568], dtype=torch.float64))])